### Numpy 기초 
- 수치해석, 수학적 계산을 목적으로 한 라이브러리
- 수치해석에 최적화 되어있음 

### Numpy 설치 
```shell
!pip install [update] numpy
```

** !가 아니라 % 인거같은데

In [14]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
%pip install update numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


#### Numpy 사용

In [16]:
import numpy as np # 보통 np로 줄여씀

In [17]:
[1,2,3,4] # 리스트

[1, 2, 3, 4]

In [18]:
# 배열 생성
arr1 = np.array([1,2,3,4]) 
arr1 # numpy 배열 

array([1, 2, 3, 4])

In [19]:
# 배열의 구조 
arr1.shape # 1차원 배열, 크기가 4 

(4,)

In [20]:
# 2차원 배열 
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
# arr2 구조 
arr2.shape

(2, 4)

In [22]:
arr3 = np.array([[1,2,3,4]])
arr3.shape

(1, 4)

In [23]:
# 넘파이 데이터타입 확인
arr3.dtype

dtype('int32')

- 넘파이 자료형
    - 부호정수 : int8, int16, int32, int64
    - 무부호정수 : uint8, uint16, uint32, uint64
    - 실수 : float8, float16, float32, float64
    - 복소수 : complex8, complex16, complex32, complex64
    - 문자열 : string_ 
    - 불린 : boolen
    - 유니코드 : unicode_
    - 파이썬 오브젝트 : object

In [24]:
# 1차원 요소 10개가 모두 0인 배열 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
# 2차원 배열, 2행 4열 모두가 0인 초기화
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# 1차원 요소 10개를 모두 1로 배열 초기화
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
# 2차원 배열, 2행 4열 모두가 1로 초기화
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# 3부터 1씩 증가, 9가 마지막인 배열 초기화
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
# 3부터 2씩 증가, 9가 마지막인 배열 초기화
np.arange(3,10,2)

array([3, 5, 7, 9])

- 사용 이유 

In [37]:
## 대량 리스트(1억) 생성
pyList = list(range(10_000_000))
npList = np.arange(10_000_000)

In [38]:
len(pyList)

10000000

In [39]:
## 파이썬 리스트 계산 처리 시간 
%timeit for _ in range(10): pyList2 = pyList * 2

1.58 s ± 50.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
## 넘파이 배열 계산 처리 시간
%timeit for _ in range(10): npList2 = npList * 2

150 ms ± 5.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


- 계산결과 = 넘파이로 수치계산을 하면 시간을 절약할 수 있음