### 파이토치 기본
- 기본 사용법

In [ ]:
import torch
import numpy as np

In [ ]:
## 파이토치 
torch.__version__

#### 파이토치 패키지 구성
- **torch**
    - 메인 네임스페이스. 텐서(진짜 기본) 및 수학함수(sin,cos,tan...) 포함. numpy와 유사한 구조
    - numpy와 쉽게 변환
- **torch.autograd** 
    - 자동 미분을 위한 함수 포함. 컨텍스트 매니저, 기반 클래스 및 함수 포함 

- **torch.nn / torch.nn.functional** 
    - nn(Neural network). 딥러닝 신경망을 구축시 필요한 데이터 구조, 레이어 정의가 포함. Rnn, LSTM 레이어 및 ReLU, MESLoss 등 Tensorflow에 있는 함수 및 모델 포함

- **toach.optim**
    - 확률적 경사 하강법(SGD, Stochastic Gradient Descent) 중심 파라미터 최적화 알고리즘 포함 

- **torch.utils.data**
    - SGD 반복 연산 시 Batch(컴퓨터 자동 백그라운드로 실행) 유틸리티가 포함

- **torch.onnx**
    - Open Neural Network eXchange 포맷의 모델 포함. onnx 확장자로 export하면 PyTorch를 Tensorflow나 다른 딥러닝, 머신러닝 라이브러리에서 사용 가능 

#### 파이토치 기초

##### 텐서(Tensor) 
- 파이토치에서 데이터를 저장하는 자료구조
- 텐서플로도 기본 텐서, numpy와 성격과 사용법이 거의 흡사 

In [ ]:
# 1차원 배열, 크기 3 으로 numpy 작성 
data = [1, 3, 5] 
np.array(data)

In [ ]:
# 1차원 배열, 크기 3 으로 tensor 작성 
torch.tensor(data)

In [ ]:
arr = [[1,2,3,4], [5,6,7,8]]
arr 

In [ ]:
# 2차원 배열, 2행 4열 numpy 
np2_data = np.array(arr)

In [ ]:
# 2차원 배열, 2행 4열 tensor
tc2_Data = torch.tensor(arr)

##### tensor 하위구조 명칭
<img src = "https://camo.githubusercontent.com/814efc38b1d8ae9cf47a24e12c8aae325fb3ab56e04c601d98c967d2a182e758/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6875676f4d4753756e672f73747564792d7079746f7263682f6d61696e2f696d616765732f746f726368303030332e706e67">

- 1차원 tensor : Vector 벡터
- 2차원 tensor : Matrix 매트릭스 
- 3차원 이상 tensor : Tensor 텐서 

In [ ]:
# 넘파이와 토치의 배열 크기 
print(np2_data.shape, tc2_Data.shape)

In [ ]:
# 넘파이의 정수 기본 타입 : int32 / 파이토치의 정수 기본 타입 : int64 
print(np2_data.dtype, tc2_Data.dtype)

In [ ]:
# 텐서를 만들때 타입을 지정해서 변경가능 
torch.tensor(data=arr, dtype=torch.float64)

##### 텐서의 데이터 
- 실수계산 시 FloatTensor, 정수 LongTensor, True/Flase는 ByteTensor 

- ByteTensor, CharTensor - int 8
- ShortTensor - int 16
- IntTensor - int 32
- LongTensor - int 64
- HalfTensor - float16
- FloatTensor  float32
- DoubleTensor - Float64 

- 참조 : https://subinium.github.io/pytorch-Tensor-Variable/

In [ ]:
## 데이터타입으로 변환시 
tc2_Data.type('torch.DoubleTensor')

##### 텐서 구조 상태 확인
- tensor.shape, tensor,.size() # 텐서의 크기
- tensor.dtype, tensor,.type()
    - dtype 타입, type() # 객체의 클래스 타입 
- tensor.ndim, tensor.dim() #텐서의 차원
- tensor.numel() # 전체 원소 갯수 

In [ ]:
# 벡터 
tns1_data = torch.tensor([1,2,3,4,5])

In [ ]:
# 매트릭스 
tns2_data = torch.tensor([[1,2,3,4],[5,6,7,8]])

In [ ]:
# 넘파이로 3차원 생성, 텐서 
tns3_data = torch.tensor(np.arrage(27).reshape(3,3,3))
tns3_data

In [ ]:
## 원소 갯수 
print(f'Vector num = {tns1_data.numel()} \nMatrix')

- 넘파이와 파이토치 텐서간 변환 쉬움
- 넘파이 함수와 동일한 함수 존재 

In [27]:
## zeros
torch.zeros(2,4) 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# 파이썬과 같이 인덱싱, 슬라이싱 가능 
tns2_data[0][1:3]

tensor([2, 3])

In [29]:
# 행렬합 
x1 = torch.tensor([[1,2,3],[4,5,6]])
x2 = torch.tensor([[1,2,3],[4,5,6]])
torch.add(x1,x2)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [30]:
# 행렬곱 
x1 = torch.tensor([[1,2,3],[4,5,6]])
x2 = torch.tensor([[1,2,3],[4,5,6]])
torch.mul(x1,x2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [31]:
# 매트릭스 연산 : 첫번째 매트릭스 열 크기와 두번째 매트리스 행크기가 일치 
x3 = torch.tensor([[1,2],[3,4],[5,6]])
torch.mm(x1, x3)

tensor([[22, 28],
        [49, 64]])

#### CPU 메모리에서 GPU메모리로 데이터 전달

In [37]:
## 현재의 데이터가 어느 메모리에 있는지 
x3.device

device(type='cpu')

In [38]:
## cpu 디바이스 = 'cpu'
cpu = torch.device('cpu')

In [43]:
## GPU 디바이스 = 'cuda'
gpu = torch.device('cuda')

In [44]:
x3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [46]:
x4 = x3.to(gpu)
x4

AssertionError: Torch not compiled with CUDA enabled